[workspace]
members = [
    "light-curve",
    "light-curve-common",
    "light-curve-dmdt",
    "light-curve-feature",
    "light-curve-interpol",
    "python",
]

[profile.release]
lto = true
codegen-units = 1
