[package]
name = "light-curve-feature"
version = "0.1.10-beta.0"
description = "Feature extractor from noisy time series"
repository = "https://github.com/hombit/light-curve"
authors = ["Konstantin Malanchev <hombit@gmail.com>"]
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "katex-header.html",
]

[dependencies]
num-traits = "0.2"
conv = "0.3"
light-curve-common = "0.1.0"

[dev-dependencies]
rand = "0.7"
criterion = "0.3"

[[bench]]
name = "benchmark"
path = "benches/lib.rs"
harness = false
