name: Publish Python packages

on:
  push:
    tags:
      - light-curve-python-v*

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15, windows-2019]
        include:
          # Publish source code among with Linux wheels
          - os: ubuntu-latest
            NOSDIST:
          - os: macos-10.15
            NOSDIST: --no-sdist
          - os: windows-2019
            NOSDIST: --no-sdist
            

    defaults:
      run:
        working-directory: python

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install maturin
      run: pip install maturin
    - name: Publish
      run: maturin publish ${{matrix.NOSDIST}} --no-strip -u __token__ -p ${{ secrets.PYPI_TOKEN }}
