name: Publish Python packages

on:
  push:
    tags:
      - light-curve-python-v*

jobs:
  publish-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fftw_feature: mkl
            arch: x86_64
          # - os: [self-hosted, linux, ARM64]
          #   fftw_feature: fftw-static
          #   arch: aarch64

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --build-arg='ARCH=${{ matrix.arch }}' --no-cache --tag maturin -f .ci/Dockerfile.maturin .ci
    - name: Build wheels for tests
      run: docker run --rm -v $(realpath light-curve-python):/io maturin build --release -i python3.6 python3.7 python3.8 python3.9 --cargo-extra-args="--no-default-features --features ${{ matrix.fftw_feature }},gsl"
    - name: Run Python tests
      run: docker run --rm -v $(realpath light-curve-python):/io --entrypoint=/bin/bash maturin -c 'python3.6 -m pip install target/wheels/*cp36*.whl && python3.7 -m pip install target/wheels/*cp37*.whl && python3.8 -m pip install target/wheels/*cp38*.whl && python3.9 -m pip install target/wheels/*cp39*.whl && tox -p --skip-pkg-install --sitepackages'
    - name: Publish packages
      run: docker run --rm -v $(realpath light-curve-python):/io maturin publish --no-sdist -i python3.6 python3.7 python3.8 python3.9 --cargo-extra-args="--no-default-features --features ${{ matrix.fftw_feature }},gsl" -u __token__ -p ${{ secrets.PYPI_TOKEN }}


  publish-macos:
    runs-on: macos-10.15

    defaults:
      run:
        working-directory: python/light-curve

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install GSL and keep static libs only
      run: |
        brew install gsl
        brew list -v gsl | grep '.dylib' | xargs rm -vf
    - name: Install tox and maturin
      run: pip install tox maturin twine
    - name: Run Python tests
      run: tox -p -q
    - name: Publish macOS packages
      run: maturin publish --cargo-extra-args="--no-default-features --features fftw-static,gsl" -i python3.6 python3.7 python3.8 python3.9 -u __token__ -p ${{ secrets.PYPI_TOKEN_LIGHT_CURVE }}
